### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by KafkaNoNeko** [IvanIsCoding/MATH460#2]
- [x] Intro
- [x] HMACs
- [x] Compare and contrast digital signatures and MACs
- [x] MACs and block ciphers (e.g. GCM)
- [x] Replay attacks (and conclusion)
- [x] Exam Questions
